# Generated by Django 4.0.1 on 2022-01-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pass_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
