# Generated by Django 4.0.1 on 2022-01-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_diet_bought_training_bought'),
        ('Accounts', '0003_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='passs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.pass'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.pass'),
        ),
    ]
